# Generated by Django 4.0.4 on 2022-09-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Nombre_producto',
            field=models.CharField(max_length=25),
        ),
    ]
