# Generated by Django 4.0.4 on 2022-09-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_alter_producto_nombre_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='fecha_compra',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
