# Generated by Django 4.0.4 on 2022-09-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_alter_ventas_fecha_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='fecha_compra',
            field=models.DateField(auto_now=True),
        ),
    ]
