# Generated by Django 4.0.4 on 2022-09-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_alter_ventas_fecha_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Nombre_cliente',
            field=models.CharField(max_length=100),
        ),
    ]
