# Generated by Django 4.0.4 on 2022-09-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_alter_cliente_nombre_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='cantidad',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='Nombre_producto',
            field=models.CharField(max_length=100),
        ),
    ]
