# Generated by Django 4.0.4 on 2022-09-18 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_ventas_cantidad_alter_producto_nombre_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='cantidad',
        ),
    ]
