# Generated by Django 4.0.4 on 2022-09-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_remove_ventas_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='cantidad',
            field=models.IntegerField(null=True),
        ),
    ]
