# Generated by Django 4.0.4 on 2022-09-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0008_ventas_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='numero_factura',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='cantidad',
            field=models.IntegerField(),
        ),
    ]
