# Generated by Django 4.0.4 on 2022-09-28 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0008_ventas_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportes',
            name='idVentas',
        ),
        migrations.AddField(
            model_name='reportes',
            name='numero_factura',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ventas',
            name='numero_factura',
            field=models.IntegerField(null=True),
        ),
    ]
