# Generated by Django 4.0.4 on 2022-09-28 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0009_remove_reportes_idventas_reportes_numero_factura_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportes',
            old_name='numero_factura',
            new_name='numero_reporte',
        ),
    ]
