# Generated by Django 4.0.4 on 2022-10-03 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0010_rename_numero_factura_reportes_numero_reporte'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportes',
            old_name='numero_reporte',
            new_name='numero_factura',
        ),
    ]
